# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUKU1eR6j-cuz5gUrjZTg1HYFjsXDCFV
"""

# Import required libraries
from gtts import gTTS
from IPython.display import Audio
import random

# List of random phrases
random_phrases = [
    "Hello, how are you today?",
    "Good morning! Hope you have a great day.",
    "It's a beautiful day outside!",
    "I am a random text-to-speech generator.",
    "The quick brown fox jumps over the lazy dog."
]

# Choose a random phrase from the list
random_text = random.choice(random_phrases)

# Define the language for TTS
language = 'en'

# Initialize gTTS object with the random text
tts = gTTS(text=random_text, lang=language, slow=False)

# Save the generated speech to an MP3 file
audio_file = "random_output.mp3"
tts.save(audio_file)

# Play the generated audio
Audio(audio_file)